policy_name: "wtw_model.pt"
use_genesis: True
dt: 0.02
stand_kp: 60.0
stand_kd: 5.0
ctrl_kp: 20
ctrl_kd: 0.5
action_scale: 0.25
lin_vel_scale: 1.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
frame_stack: 5
num_single_obs: 61                       # length of single step observation
num_gaits: 4                             # equals length of theta_fl
gait_period_range: [0.3, 0.6]
base_height_target_range: [0.2, 0.34]
foot_clearance_target_range: [0.04, 0.12]
pitch_target_range: [-0.3, 0.3]
theta_fl: [0.0, 0.0, 0.5, 0.0]
theta_fr: [0.5, 0.0, 0.0, 0.0]
theta_rl: [0.5, 0.0, 0.5, 0.5]
theta_rr: [0.0, 0.0, 0.0, 0.5]
stand_pos: [
    0.0,
    0.8,
    -1.5,
    0.0,
    0.8,
    -1.5,
    0.0,
    0.8,
    -1.5,
    0.0,
    0.8,
    -1.5
]
sit_pos: [
    0.04,
    1.3,
    -2.87,
    -0.02,
    1.29,
    -2.86,
    -0.33,
    1.27,
    -2.81,
    0.32,
    1.28,
    -2.87
]
